# Generated by Django 2.1.3 on 2018-12-01 17:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sort_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('sort_name', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=20)),
                ('aliases', djongo.models.fields.ListField(verbose_name=djongo.models.fields.EmbeddedModelField(model_container='Aliase', null=True))),
                ('begin', djongo.models.fields.EmbeddedModelField(model_container='Begin', null=True)),
                ('end', djongo.models.fields.EmbeddedModelField(model_container='End', null=True)),
                ('tags', djongo.models.fields.ListField(verbose_name=djongo.models.fields.EmbeddedModelField(model_container='Tag', null=True))),
                ('rating', djongo.models.fields.EmbeddedModelField(model_container='Rating', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Begin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
